# Generated by Django 3.2.16 on 2023-01-30 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Название', max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(help_text='Описание', max_length=250, verbose_name='Описание')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taskcase_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTaskRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('CHECK', 'На проверке'), ('REVISION', 'На доработку'), ('ACCEPT', 'Принято')], default='NEW', max_length=10)),
                ('task_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_relation', to='tasks.taskcase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_relation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTaskCaseRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('complete', models.BooleanField(default=False, verbose_name='Выполнение')),
                ('task_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_case_relation', to='tasks.taskcase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_case_relation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Название', max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(help_text='Описание', max_length=250, verbose_name='Описание')),
                ('answer', models.TextField(verbose_name='Решение')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_author', to=settings.AUTH_USER_MODEL)),
                ('task_case', models.ManyToManyField(blank=True, related_name='tasks', to='tasks.TaskCase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
