# Generated by Django 3.2.16 on 2023-01-31 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20230131_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertaskrelation',
            name='task_case',
        ),
        migrations.AddField(
            model_name='usertaskrelation',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_relation', to='tasks.task'),
            preserve_default=False,
        ),
    ]
