# Generated by Django 3.2.16 on 2023-02-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20230131_0703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-created',), 'verbose_name': 'Вопросы', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AddField(
            model_name='usertaskrelation',
            name='answer',
            field=models.TextField(default=1, verbose_name='Ответ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(help_text='Описание', max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_case',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tasks.TaskCase', verbose_name='Группа вопросов'),
        ),
        migrations.AlterField(
            model_name='taskcase',
            name='description',
            field=models.TextField(help_text='Описание', max_length=250, verbose_name='Описание'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
