# Generated by Django 3.2.16 on 2023-02-01 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20230201_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertaskrelation',
            name='answer',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='Правки')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tasks.usertaskrelation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='Ответ')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tasks.usertaskrelation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
