# Generated by Django 3.2.16 on 2023-02-03 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20230201_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='relation',
        ),
        migrations.AddField(
            model_name='review',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tasks.answer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(help_text='Описание', max_length=2000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='taskcase',
            name='description',
            field=models.TextField(help_text='Описание', max_length=2000, verbose_name='Описание'),
        ),
    ]
