# Generated by Django 3.2.16 on 2023-02-08 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20230203_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcase',
            options={'ordering': ('-created',), 'verbose_name': 'Блоки', 'verbose_name_plural': 'Блоки'},
        ),
    ]
