# Generated by Django 3.2.16 on 2023-02-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='description',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='title',
        ),
    ]
