# Generated by Django 3.2.16 on 2023-02-14 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0011_variant_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to=settings.AUTH_USER_MODEL),
        ),
    ]
