# Generated by Django 3.2.16 on 2023-02-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_variant_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='author',
        ),
    ]
