# Generated by Django 3.2.16 on 2023-02-16 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_remove_variant_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskcase',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usertaskrelation',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('CHECK', 'На проверке'), ('REVISION', 'На доработку'), ('ACCEPT', 'Принято'), ('WRONG', 'Ошибка')], default='NEW', max_length=10),
        ),
        migrations.AlterField(
            model_name='variant',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='tasks.task'),
        ),
    ]
