# Generated by Django 3.2.16 on 2023-02-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_taskcase_options'),
        ('users', '0004_auto_20230209_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(blank=True, help_text='Вопросы', null=True, related_name='users', through='tasks.UserTaskRelation', to='tasks.Task', verbose_name='Вопросы'),
        ),
    ]
