# Generated by Django 3.2.16 on 2023-02-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_remove_variant_author'),
        ('users', '0005_user_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='variants',
            field=models.ManyToManyField(blank=True, help_text='Варианты', null=True, related_name='users', to='tasks.Variant', verbose_name='Варианты'),
        ),
    ]
